### ISSUE TITLE
Make (last key pressed) a custom reporter

### ISSUE THREAD

**Issue by PPPDUD** [TurboWarp/scratch-vm#87] opened 2022-09-18 20:15 UTC
In TurboWarp, it will act like the is compiled block.
In Scratch, it just reports a blank string.

I think there should be a toggle allowing one to change if it's a custom block or a TurboWarp block.

**Comment by GarboMuffin** [comment] 2022-10-26 18:53
Duplicate of #44

**Closed by GarboMuffin** 2022-10-26 18:53 UTC
